export const products = [
  {
    id: 1,
    bestSeller: false,
    title: 'Effaclar',
    quickInfo:
      'About Effaclar mat is for oily skin prone to imperfections and shine.',
    info: 'About Effaclar mat is for oily skin prone to imperfections and shine. It is specifically formulated for sensitive skin.Used daily it helps to limit the appearance of pores and shine by reducing excess sebum. Oily skin is moisturised and the mattifying properties help to control shine all day. Skin feels smoother. Formula now contains Sebulyse.Oil-free texture with Perlite',
    img: [
      './assets/jpg/prdt-img/moisturiser-La Roche-Posay.jpg',
      './assets/jpg/prdt-img/La Roche-Posay.jpg',
    ],
    company: 'La Roche-Posay',
    productType: 'moisturiser',
    price: 11.95,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    bestSeller: false,
    title: 'Anthelios',
    quickInfo:
      'Invisible fragrance-free 50ml pocket-size liquid sun cream from Anthelios La Roche Posay.',
    info: 'Invisible fragrance-free 50ml pocket-size liquid sun cream from Anthelios La Roche Posay. Enriched with La Roche Posay thermal spring water. The new, invisible liquid texture of this sun cream means no white streaks and flawless skin.The convenient pocket-size bottle makes it easy to carry to the beach.',
    img: ['./assets/jpg/prdt-img/sunc cream-La Roche-Posay.png'],
    company: 'La Roche-Posay',
    productType: 'sun cream',
    price: 12.5,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    bestSeller: false,
    title: 'C E Feluric',
    quickInfo:
      'ydrating B5 is an oil-free moisturizer combined with vitamin B5',
    info: 'Hydrating B5 is an oil-free moisturizer combined with vitamin B5 and hyaluronic acid, to help prevent moisture loss from the skin. It can be used alone or with a daily moisturizer to provide extra hydration. A good combination with Retinol and is ideal for all skin types.',
    img: [
      './assets/jpg/prdt-img/serum-SkinCeuticals.jpg',
      './assets/jpg/prdt-img/SkinCeuticals.jpeg',
    ],
    company: 'SkinCeuticals',
    productType: 'serum',
    price: 140,
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    bestSeller: true,
    title: 'Triple Lipid Restore',
    quickInfo: 'A.G.E. Eye Complex is an anti-wrinkle eye cream.',
    info: 'A.G.E. Eye Complex is an anti-wrinkle eye cream that contains a combination of ingredients formulated to target the visible signs of ageing skin caused by Advanced Glycation End-products (A.G.E.)',
    img: './assets/jpg/prdt-img/eye complex-SkinCeuticals.jpg',
    company: 'SkinCeuticals',
    productType: 'eye Complex',
    inCart: false,
    price: 135,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    bestSeller: false,
    title: 'skin perfecting',
    quickInfo:
      'ILightweight lotion softens and hydrates skin while diminishing blackheads and blemishes.',
    info: 'This gentle exfoliating lotion with 2% BHA (salicylic acid) removes built-up dead skin cells to reveal radiant, silky-soft skin. Formulated with a blend of plant oils and antioxidants, this moisturising lotion softens dry, rough skin and soothes redness while diminishing blackheads and blemishes.',
    img: [`./assets/jpg/prdt-img/skin-perfecting-paula's choice.jpg`],
    company: `Paula's Choice`,
    productType: 'moisturising',
    price: 31,
    inCart: false,
    count: 0,
    total: 0,
  },
];
